# Generated by Django 4.0.3 on 2022-04-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(help_text='ex: Corsa', max_length=100, verbose_name='Titulo')),
                ('plate', models.CharField(max_length=8, verbose_name='Placa')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor total')),
                ('observation', models.CharField(help_text='informe alguma observação', max_length=250, null=True, verbose_name='Observações')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição do serviço ou peça', max_length=100, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.notes')),
            ],
        ),
    ]
