# Generated by Django 4.0.3 on 2022-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='plate',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa'),
        ),
    ]
