# Generated by Django 4.0.3 on 2022-04-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notes_observation_notes_situacion_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='situacion',
            new_name='situation',
        ),
    ]
