# Generated by Django 4.0.3 on 2022-04-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_situacion_notes_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notes'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notes'),
        ),
    ]
